### ISSUE TITLE
OSX not extracting the daemon

### ISSUE THREAD

**Issue by dekm** [unigrid-project/janus-java#138]
OSX is having an issue on some macs extracting all the files needed.

Version: 1.0.9

![Capture d’écran 2022-12-12 à 21 56 04](https://user-images.githubusercontent.com/9221328/207327685-3e3fc641-62ab-4b08-b57b-512876f963b9.png)

**Comment by adam-waldenberg** [comment]
Do we have any other information? Any exceptions or anything else to go on?
