### ISSUE TITLE
We have detected an issue with your wallet. Lease restart to resolve the issue.

### ISSUE THREAD

**Issue by sohailharen** [unigrid-project/janus-java#168]
### Operating System

- [x] Windows
- [ ] Linux
- [ ] macOS

### Operating System Version

Please specify the version of your operating system (e.g., Windows 11, Ubuntu 20.04, macOS 12).

### Janus version

1. Installer version:
2. FX version (shown during the startup): 

### Description

Please provide a clear and concise description of the issue you are experiencing.

### Steps to Reproduce

Please list the steps to reproduce the issue, if applicable:

1. Step 1
4. Step 2
5. Step 3

### Expected Behavior

Please describe what you expected to happen.

### Actual Behavior

Please describe what actually happened.

### Screenshots

If applicable, add screenshots to help explain your issue. You can simply drag and drop the images here.

### Additional Information

Please provide any additional information that might help us understand the issue, such as error messages, logs, or hardware specifications.

**Comment by sohailharen** [comment]
windows 11,
![WhatsApp Image 2023-04-27 at 12 10 17](https://user-images.githubusercontent.com/131952429/234798989-2b5f9417-0c49-4e5e-8700-040420cb52f6.jpeg)
![WhatsApp Image 2023-04-27 at 12 18 30](https://user-images.githubusercontent.com/131952429/234799000-edb33b09-1155-48ad-9f78-b2ed00aa04ce.jpeg)

**Comment by dekm** [comment]
That is a connection with the daemon issue. From the debug log it appears their local blockchain is corrupted. The quickest way to fix that is to remove the local chain data.

https://docs.unigrid.org/docs/unigrid-janus/troubleshooting/#force-download-blockchain

**Comment by sohailharen** [comment]
[debug.log](https://github.com/unigrid-project/janus-java/files/11341091/debug.log)

**Comment by dekm** [comment]
They also need to make sure everything is shut down before doing this.

https://docs.unigrid.org/docs/unigrid-janus/troubleshooting/#wallet-stuck-on-startup-screen

**Comment by dekm** [comment]
From that log the wallet has never fully synced. We fixed an issue causing slow sync times that was released yesterday. So he should remove the chain data once more and start Janus. I believe this will resolve his issues.

**Comment by sohailharen** [comment]
> From that log the wallet has never fully synced. We fixed an issue causing slow sync times that was released yesterday. So he should remove the chain data once more and start Janus. I believe this will resolve his issues.

even the backup file too?

**Comment by dekm** [comment]
> > From that log the wallet has never fully synced. We fixed an issue causing slow sync times that was released yesterday. So he should remove the chain data once more and start Janus. I believe this will resolve his issues.
> 
> even the backup file too?

The instructions on the docs page explain all of that. You should never have to throw out a wallet file.
