### ISSUE TITLE
very occasionally it opens but with a failure 

### ISSUE THREAD

**Issue by sohailharen** [unigrid-project/janus-java#169]
[32ventures.io.txt](https://github.com/unigrid-project/janus-java/files/11351170/32ventures.io.txt)

### Operating System

- [ ] macOS AppleBook Air  Apple M1

### Operating System Version

Please specify the version of your operating system (e.g., Windows 11, Ubuntu 20.04, macOS 12).

### Janus version
1.0.14

1. Installer version: 1.0.11
2. FX version (shown during the startup): 

### Description

Please provide a clear and concise description of the issue you are experiencing.
very occasionally it opens but with a failure
### Steps to Reproduce

Please list the steps to reproduce the issue, if applicable:

1. Step 1
4. Step 2
5. Step 3

### Expected Behavior

Please describe what you expected to happen.

### Actual Behavior

Please describe what actually happened.

### Screenshots

If applicable, add screenshots to help explain your issue. You can simply drag and drop the images here.

### Additional Information

Please provide any additional information that might help us understand the issue, such as error messages, logs, or hardware specifications.

**Comment by dekm** [comment]
`Error: Error loading wallet.dat: Wallet corrupted`

They need to replace the wallet.dat with one from the backups directoy and rename it to wallet.dat

**Comment by dekm** [comment]
Also delete the budget.dat file before you restart. I would do a hard drive scan on your computer to make sure everything is ok.

**Comment by sohailharen** [comment]
> Also delete the budget.dat file before you restart. I would do a hard drive scan on your computer to make sure everything is ok.

where it is located into which folder?

**Comment by dekm** [comment]
> > Also delete the budget.dat file before you restart. I would do a hard drive scan on your computer to make sure everything is ok.
> 
> where it is located into which folder?

For mac it is `~/Library/Application Support/UNIGRID/`

![image](https://user-images.githubusercontent.com/9221328/235098810-463ddfe2-cb95-4bde-82b1-46d352e4a806.png)

and the backups look like this
![image](https://user-images.githubusercontent.com/9221328/235098937-2b176f3f-96a2-4216-baef-241feac6bd6d.png)

**Comment by sohailharen** [comment]
1.deleted the budget file.
2. replaced the wallet.dat 
still the wallet is causing the issue

**Comment by sohailharen** [comment]
[debug (2) 32 venture.txt](https://github.com/unigrid-project/janus-java/files/11354947/debug.2.32.venture.txt)
