### ISSUE TITLE
Janus Not responding on startup !!

### ISSUE THREAD

**Issue by DripsukCal** [unigrid-project/janus-java#170]
### Operating System

- [x ] Windows
- [ ] Linux
- [ ] macOS

### Operating System Version

Please specify the version of your operating system (e.g., Windows 11, Ubuntu 20.04, macOS 12).

Windows 10 

### Janus version

1. Installer version:    1.0.11
2. FX version (shown during the startup): 

### Description

When startup of Janus ..NOT Responding in Task Manager 

### Steps to Reproduce

Please list the steps to reproduce the issue, if applicable:

1. Step 1 ..Deleted old wallet ,  reninalled from UNIGRID web V 1.011
4. Step 2 ..Turned off Defendor and Anivirus ,
5. Step 3..RUN as Administrator 

### Expected Behavior

Wallet should open and look for updates 

### Actual Behavior

Nothing ..Wallet startup screen and then NOT Responding error .

### Screenshots

If applicable, add screenshots to help explain your issue. You can simply drag and drop the images here.

### Additional Information

Please provide any additional information that might help us understand the issue, such as error messages, logs, or hardware specifications.

**Comment by adam-waldenberg** [comment]
No debug.log provided. Closing.
