### ISSUE TITLE
when internet get disrupted the wallet shows that it is fully synced but actually it is not.

### ISSUE THREAD

**Issue by sohailharen** [unigrid-project/janus-java#171]
### Operating System

- [ ] Windows 11
- [ ] Linux
- [ ] macOS

### Operating System Version

Please specify the version of your operating system (e.g., Windows 11, Ubuntu 20.04, macOS 12).

### Janus version

1. Installer version:
2. FX version (shown during the startup): 

### Description

Please provide a clear and concise description of the issue you are experiencing.

### Steps to Reproduce

Please list the steps to reproduce the issue, if applicable:

1. Step 1
4. Step 2
5. Step 3

### Expected Behavior

Please describe what you expected to happen.

### Actual Behavior

Please describe what actually happened.

### Screenshots

If applicable, add screenshots to help explain your issue. You can simply drag and drop the images here.

### Additional Information

Please provide any additional information that might help us understand the issue, such as error messages, logs, or hardware specifications.

**Comment by dekm** [comment]
Closing this since the wallet has no way to check whether it is synced or not if there is no internet connection. Once cosmos sdk is integrated it will either be connected or not.
