### ISSUE TITLE
gridnode error

### ISSUE THREAD

**Issue by dekm** [unigrid-project/janus-java#173]
### Operating System

Likely all OSs noticed on Linux
- [x] Windows
- [x] Linux
- [x] macOS

### Janus version

1. Installer version: 1.0.11
2. FX version (shown during the startup): 1.0.14

### Description

Gridnodes not starting.

Wallet is unlocked and attempting to start the gridnodes debug log outputs.

`2023-04-29 09:32:42 CActiveGridnode::CreateBroadcast() - Could not allocate vin `

Checked the vin in the explorer and they are correct with 3000 tokens.

After some time if you try to press start again the wallet locks up and completely freezes.

**Comment by sohailharen** [comment]
my wallet does not show the gridnodes

**Comment by sohailharen** [comment]
my wallet does not show the gridnodes
[debug.log](https://github.com/unigrid-project/janus-java/files/11360600/debug.log)

**Comment by dekm** [comment]
This was related to the old conf file no longer working. We renamed everything to gridnode from masternode. All new installs will resolve this in the installer script. 

To fix already running nodes this script can be run to update all the conf files and restart the containers. 

 ```
bash -ic "$(wget -4qO- -o- raw.githubusercontent.com/unigrid-project/unigrid-installer/main/scripts/fixconfs.sh)" ; source ~/.bashrc
```
