### ISSUE TITLE
wallet is not opening

### ISSUE THREAD

**Issue by sohailharen** [unigrid-project/janus-java#189]
Wallet has worked well for several years until the update that was made on April 30
the operating system is 64 bit, Windows 10 pro
version 22H2
OS Build 19045.2965
experience Windows Feature Experience Pack 1000.19041.1000.0
processor is Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz 4.00 GHz
RAM 16GB
The problem is that it only shows this screen for hours and I have to end up killing it
the debug file that I sent you is the only one I have
I already tried several backups, I even installed the wallet on a laptop that I no longer use and opened it, then I used that wallet.dat and the same
I grabbed the wallet.dat from a mac and it doesn't go past that screen, sometimes when I turn it on it says connected with the hedgehog and that's it

I have also opened it as administered without positive result
[debug (5).log](https://github.com/unigrid-project/janus-java/files/11602498/debug.5.log)

**Comment by adam-waldenberg** [comment]
Looks like a firewall or antivirus issue - not Janus. Closing.
