### ISSUE TITLE
Determine how many gridnodes a user can run

### ISSUE THREAD

**Issue by dekm** [unigrid-project/janus-java#208]
This will require pulling the required amount for a gridnode from hedgehog and using the amount delegated by account. 

Pull amount required from hedgehog how many tokens on node takes.
Pull accounts delegated amount to gridnode.

Divide delegated amount by required amount.

For example if its 2000 tokens and they delegate 4000.. 4000/2000 = 2

**Comment by andersgun82** [comment]
Added calculation of how many gridnodes user can run based on delegated amount
