### ISSUE TITLE
Should pull validators from the chain

### ISSUE THREAD

**Issue by dekm** [unigrid-project/janus-java#214]
Info on the validator list should be pulled from the network.

From rest this list can be pulled here.

https://rest-testnet.unigrid.org/cosmos/staking/v1beta1/validators

This data should be placed in a model for storage locally.

Users should just be shown a dropdown list with the NAME of the Validator and it's % only. When the select a validator from the list to delegate to we use that object IDs valoper address.

**Comment by andersgun82** [comment]
Validators list shown in combobox in wallet (Validator name, commission in %)
