### ISSUE TITLE
add method to switch delegator

### ISSUE THREAD

**Issue by dekm** [unigrid-project/janus-java#222]
In cosmos you can switch who your delegator is. This would likley need to be a button next to each delegator in the list on the staking view.

This would be a transaction on the network that requires a signature.

We also will need an undelegate for staking delegations. This should be separate for each validator you are staking on.
Like this in the current explorer.

![Image](https://github.com/unigrid-project/janus-java/assets/9221328/6dd88338-f460-45ef-bfb2-8d6bf39339b0)

**Comment by nathan1132** [comment]
users can now change delegator and unstake tokens
