### ISSUE TITLE
extra item appearing in the staking view list

### ISSUE THREAD

**Issue by dekm** [unigrid-project/janus-java#244]
at the bottom of the staking view when you delegate once there is an extra item appearing at the bottom. 

![Image](https://github.com/unigrid-project/janus-java/assets/9221328/c82045c9-dba7-48c2-90a8-910041a1c9a2)

**Comment by PvlSport** [comment]
was fixed in https://github.com/orgs/unigrid-project/projects/11/views/1?pane=issue&itemId=59438184
