### ISSUE TITLE
we need to determine the spendable balance available from vesting

### ISSUE THREAD

**Issue by dekm** [unigrid-project/janus-java#250]
This should be displayed so people have a way to determine what is available for sending. This does not affect what they can stake as 100% is available for staking and gridnodes. It is only the amount they are able to send to another account.

To get the spendable balance we can use the bank module

curl https://rest-devnet.unigrid.org/cosmos/bank/v1beta1/spendable_balances/unigrid1attpyzmtq9k4r42gkglnx0edgukjh969jrsmn8 | jq

which will return something like this

```
{
  "balances": [
    {
      "denom": "uugd",
      "amount": "2170000000000"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "1"
  }
}
```

**Comment by PvlSport** [comment]
done in [265e51823f28ec77bb62395f5dcc0de33a220e45]
