### ISSUE TITLE
Optional values must be checked before being accessed JAVA-E1013

### ISSUE THREAD

**Issue by philipjonsen** [unigrid-project/janus-java#53]
DESCRIPTION
Do not call Optional.get() without first confirming whether there is a valid value present through Optional.isPresent().

java.util.Optional is a very useful tool for avoiding the usage of null in a codebase. However, even an Optional can be unsafe if it does not contain a value when used.

If get() is called without calling isPresent(), an exception could be raised, which would mean the Optional is no better than a normal nullable value.

Examples:
Bad Practice
Optional<Integer> result = someComputation();

// Will throw if result is empty.
int intVal = result.get();

result = Optional.empty();

result.get(); // Throws!

Recommended:
There are 2 ways to fix this:

Only use get() after a condition that checks if the Optional value is valid.

if (!result.isPresent()) return;

int intVal = result.get();
Another useful feature of Optional is the ifPresent() method, which accepts a lambda taking the value of the Optional as an argument:

result.ifPresent(value -> {
    // ...
});
References
Oracle Java SE 11 JavaDocs - [java.util.Optional](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html)

dragDirection.isPresent() was not called before this call to get()

[src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java](https://github.com/philipjonsen/janus-java-unigrid/blob/master/src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java#L43-L43)
Seen an hour ago
 40	private double y2;
 41
 42	private void refreshCoordinates(double screenX, double screenY) {
 43		if (dragDirection.get() == Direction.NORTH || dragDirection.get() == Direction.NORTHEAST
 44			|| dragDirection.get() == Direction.NORTHWEST) {
 45			y1 = origin.getMinY() - (clickedPoint.getY() - screenY);
 46		}
dragDirection.isPresent() was not called before this call to get()

src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java
Seen an hour ago
 50			x2 = origin.getMaxX() - (clickedPoint.getX() - screenX);
 51		}
 52
 53		if (dragDirection.get() == Direction.SOUTHEAST || dragDirection.get() == Direction.SOUTH
 54			|| dragDirection.get() == Direction.SOUTHWEST) {
 55			y2 = origin.getMaxY() - (clickedPoint.getY() - screenY);
 56		}

dragDirection.isPresent() was not called before this call to get()

[src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java](https://github.com/philipjonsen/janus-java-unigrid/blob/master/src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java#L43-L43)
Seen an hour ago
 40	private double y2;
 41
 42	private void refreshCoordinates(double screenX, double screenY) {
 43		if (dragDirection.get() == Direction.NORTH || dragDirection.get() == Direction.NORTHEAST
 44			|| dragDirection.get() == Direction.NORTHWEST) {
 45			y1 = origin.getMinY() - (clickedPoint.getY() - screenY);
 46		}
dragDirection.isPresent() was not called before this call to get()

src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java
Seen an hour ago
 46		}
 47
 48		if (dragDirection.get() == Direction.NORTHEAST || dragDirection.get() == Direction.EAST
 49			|| dragDirection.get() == Direction.SOUTHEAST) {
 50			x2 = origin.getMaxX() - (clickedPoint.getX() - screenX);
 51		}
 52
dragDirection.isPresent() was not called before this call to get()

src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java
Seen an hour ago
 45			y1 = origin.getMinY() - (clickedPoint.getY() - screenY);
 46		}
 47
 48		if (dragDirection.get() == Direction.NORTHEAST || dragDirection.get() == Direction.EAST
 49			|| dragDirection.get() == Direction.SOUTHEAST) {
 50			x2 = origin.getMaxX() - (clickedPoint.getX() - screenX);
 51		}
dragDirection.isPresent() was not called before this call to get()

src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java
Seen an hour ago
 45			y1 = origin.getMinY() - (clickedPoint.getY() - screenY);
 46		}
 47
 48		if (dragDirection.get() == Direction.NORTHEAST || dragDirection.get() == Direction.EAST
 49			|| dragDirection.get() == Direction.SOUTHEAST) {
 50			x2 = origin.getMaxX() - (clickedPoint.getX() - screenX);
 51		}
dragDirection.isPresent() was not called before this call to get()

src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java
Seen an hour ago
 41
 42	private void refreshCoordinates(double screenX, double screenY) {
 43		if (dragDirection.get() == Direction.NORTH || dragDirection.get() == Direction.NORTHEAST
 44			|| dragDirection.get() == Direction.NORTHWEST) {
 45			y1 = origin.getMinY() - (clickedPoint.getY() - screenY);
 46		}
 47

dragDirection.isPresent() was not called before this call to get()

[src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java](https://github.com/philipjonsen/janus-java-unigrid/blob/master/src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java#L59-L59)
Seen an hour ago
 56		}
 57
 58		if (dragDirection.get() == Direction.SOUTHWEST || dragDirection.get() == Direction.WEST
 59			|| dragDirection.get() == Direction.NORTHWEST) {
 60			x1 = origin.getMinX() - (clickedPoint.getX() - screenX);
 61		}
 62	}
dragDirection.isPresent() was not called before this call to get()

src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java
Seen an hour ago
 51		}
 52
 53		if (dragDirection.get() == Direction.SOUTHEAST || dragDirection.get() == Direction.SOUTH
 54			|| dragDirection.get() == Direction.SOUTHWEST) {
 55			y2 = origin.getMaxY() - (clickedPoint.getY() - screenY);
 56		}
 57
dragDirection.isPresent() was not called before this call to get()

src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java
Seen an hour ago
 55			y2 = origin.getMaxY() - (clickedPoint.getY() - screenY);
 56		}
 57
 58		if (dragDirection.get() == Direction.SOUTHWEST || dragDirection.get() == Direction.WEST
 59			|| dragDirection.get() == Direction.NORTHWEST) {
 60			x1 = origin.getMinX() - (clickedPoint.getX() - screenX);
 61		}
dragDirection.isPresent() was not called before this call to get()

src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java
Seen an hour ago
 55			y2 = origin.getMaxY() - (clickedPoint.getY() - screenY);
 56		}
 57
 58		if (dragDirection.get() == Direction.SOUTHWEST || dragDirection.get() == Direction.WEST
 59			|| dragDirection.get() == Direction.NORTHWEST) {
 60			x1 = origin.getMinX() - (clickedPoint.getX() - screenX);
 61		}
dragDirection.isPresent() was not called before this call to get()

[src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java](https://github.com/philipjonsen/janus-java-unigrid/blob/master/src/main/java/org/unigrid/janus/view/decorator/ResizableWindowDecorator.java#L54-L54)
Seen an hour ago
 50			x2 = origin.getMaxX() - (clickedPoint.getX() - screenX);
 51		}
 52
 53		if (dragDirection.get() == Direction.SOUTHEAST || dragDirection.get() == Direction.SOUTH
 54			|| dragDirection.get() == Direction.SOUTHWEST) {
 55			y2 = origin.getMaxY() - (clickedPoint.getY() - screenY);
 56		}

**Comment by adam-waldenberg** [comment]
In this case, having Optional.get() failing is exactly what we want.

This class uses an `Optional.empty()` and it's private for this class. If no direction is set, `get()``will throw a `NoSuchElementException` exception, which is perfect in this case. if the direction is not set, the internal state is wrong and this class should fail.

Closing this one.
