### ISSUE TITLE
Non-static nested class found JAVA-W1019

### ISSUE THREAD

**Issue by philipjonsen** [unigrid-project/janus-java#54]
DESCRIPTION
This nested class is declared without a static modifier, meaning all instances of the class will hold a reference to an instance of the enclosing class.

The Java analyzer has detected that there are no explicit references to the enclosing class here, meaning this nested class can be safely treated as static.

Consider adding a static modifier to the nested class.

Non-static nested classes are generally known as "inner" classes.

Examples
Bad Practice
class Outer {

    class Inner {
        // ...
    }

    // ...
}
There are a number of things one should be aware of when using inner classes: * An instance of Inner will contain a reference to an instance of Outer. * If the Inner instance continues to exist after all other references to the Outer instance are deleted, the Outer instance will still exist because of the reference held by the still-alive Inner class. * The syntax for instantiating a nested class is relatively obscure, and may confuse future code maintainers. * Referring to private fields of the enclosing class from the nested class requires Java to generate synthetic accessor methods for that sole purpose, bloating the class's bytecode.

Recommended
Declare the nested class as static if possible.

class Outer {
    static class Inner {
        // ...
    }

    // ...
}
Exceptions
If the inner class refers to the outer class's instance fields, this issue will not be reported.

References
Oracle Java Tutorials - [Nested Classes](https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html)
Oracle Java 11 Language Specification - Section [8.1.3](https://docs.oracle.com/javase/specs/jls/se11/html/jls-8.html#jls-8.1.3) - Inner Classes and Enclosing Instances

LoadReport will hold a reference to the enclosing class instance, is this required?

[src/main/java/org/unigrid/janus/model/TransactionList.java](https://github.com/philipjonsen/janus-java-unigrid/blob/master/src/main/java/org/unigrid/janus/model/TransactionList.java#L181-L191)
Seen an hour ago
178	}
179
180	@Data
181	public class LoadReport {
182		private int oldSize;
183		private int newCount;
184		private int newSize;
185
186		public LoadReport(int size) {
187			this.oldSize = size;
188			this.newCount = 0;
189			this.newSize = size;
190		}
191	}
192
193}

**Comment by jaho8** [comment]
- #40 [_****_](url
Bitcoin. Ethereum)
